name: notes_de_frais
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  google_mlkit_text_recognition: ^0.11.0
  file_picker: ^8.0.5
  pdfx: ^2.5.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  mime: ^1.0.5

  # Nouvelles dÃ©pendances
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ajout pour charger le fichier .env
  assets:
    - .env